/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import {useCylinder} from '@react-three/cannon'


export default function Model(props) {
  const { nodes, materials } = useGLTF('/superMarioCoinglb.glb')
  const [ref, api] = useCylinder(() => ({mass: 1, position: props.position, scale: props.scale,rotation: [10, 5, 0], args: [0.5, 0.5, 0.1, 5]}))

  return (
    <group ref={ref} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[1, 1, 1.27]}>
            <mesh geometry={nodes['Cylinder001_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/superMarioCoinglb.glb')
