/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CheckMark(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/checkMark.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[11.51, 82.47, -2.38]}>
            <mesh castShadow
              geometry={nodes.yes__yes__0.geometry}
              material={materials.material}
              position={[0, 0, 0]}
              scale={[0.5, 0.5, 0.5]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/checkMark.glb')
