/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ListObject(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ListObject.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[78, 51, -1]}>
        <mesh
          geometry={nodes.note_icon_note_icon_0.geometry}
          material={materials.note_icon}
          position={[-0.43, -0.3, -0.35]}
        />
      </group>
      <group position={[90, 57, 6]} rotation={[0, 0, -0.62]}>
        <mesh geometry={nodes.pencil_pencil_0.geometry} material={materials.pencil} position={[-0.32, 0.13, -0.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('/ListObject.glb')
