/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MailIcon(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mailIcon.glb')
  return (
    <group ref={group} {...props} dispose={null} castShadow>
      <group rotation={[-Math.PI / 2, 0, 0]} castShadow receiveShadow>
        <mesh castShadow geometry={nodes.Mesh_0.geometry} material={materials['Material.001']} />
        <mesh castShadow geometry={nodes.Mesh_1.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/mailIcon.glb')
