/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function NewGraph(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/newGraph.glb')
  return (
    <group castShadow ref={group} {...props} dispose={null}>
      <group castShadow rotation={[-Math.PI / 2, 0, 0]}>
        <group castShadow rotation={[Math.PI / 2, 0, 0]}>
          <group castShadow position={[0, 2.07, 0]} scale={1.12}>
            <mesh castShadow geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
            <mesh castShadow geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
          </group>
          <group position={[0, 0.92, 0]} scale={[0.65, 0.78, 0.65]}>
            <mesh castShadow geometry={nodes.Object_7.geometry} material={materials['1.005']} />
          </group>
          <group position={[0, 1.83, 0.22]} rotation={[0, -1.57, 0]} scale={0.44}>
            <mesh castShadow geometry={nodes.Object_9.geometry} material={materials['1.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/newGraph.glb')
