/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SmallPile(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/smallPile.glb')
  return (
    <group castShadow ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow geometry={nodes.Mesh_0.geometry} material={nodes.Mesh_0.material} />
        <mesh castShadow geometry={nodes.Mesh_1.geometry} material={nodes.Mesh_1.material} />
        <mesh castShadow geometry={nodes.Mesh_2.geometry} material={nodes.Mesh_2.material} />
        <mesh castShadow geometry={nodes.Mesh_3.geometry} material={nodes.Mesh_3.material} />
        <mesh castShadow geometry={nodes.Mesh_4.geometry} material={nodes.Mesh_4.material} />
        <mesh castShadow geometry={nodes.Mesh_5.geometry} material={nodes.Mesh_5.material} />
        <mesh castShadow geometry={nodes.Mesh_6.geometry} material={nodes.Mesh_6.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/smallPile.glb')
