/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SotChest(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/SotChest.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[4.63, 132.59, 0.51]} rotation={[-Math.PI, 0, -Math.PI]}>
            <group position={[4.93, -32.88, 387.98]}>
              <mesh castShadow geometry={nodes.chest_low_optimise_chest_low_0.geometry} material={materials.chest_low} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/SotChest.glb')
