/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import {useCylinder} from '@react-three/cannon'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/superMarioCoinglb.glb')
  const [ref, api] = useCylinder(() => ({mass: 1, position: props.position, args: [0.5, 0.5, 0.1, 5]}))


  return (
    <group ref={ref} position={props.position} dispose={null} onUpdate={self => console.log('props have been updated')}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.0019}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]} scale={[1, 1, 1.27]}>
            <mesh geometry={nodes['Cylinder001_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/superMarioCoinglb.glb')
