DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  budget_id INTEGER NOT NULL REFERENCES budgets(id) ON DELETE CASCADE,
  spending_limit MONEY NOT NULL DEFAULT 0
);